"""Shared fixtures.

There is no platform-staff allowlist any more: "administrator" means
membership of the admin app account (AUTH_ADMIN_ACCOUNT_ID), which is a fact
about the user's own record. ``admin_token`` below is the only way to get one.

Every test runs against in-memory repositories — the suite never touches a
real MongoDB and never needs credentials. With AUTH_MONGO_URI unset,
``init_repository()`` (called from the app's lifespan) already falls back to
fresh ``InMemory*Repository`` instances, so a function-scoped ``client``
fixture that re-enters the TestClient context per test gets a clean slate for
free — no monkeypatching needed.

The env defaults below are set *before* any app import because settings
objects are module-level singletons built at import time; real environment
variables outrank .env in pydantic-settings, so this also keeps the suite
hermetic on a developer machine that has a fully populated .env.
"""
from __future__ import annotations

import os

os.environ.setdefault("AUTH_MONGO_URI", "")
os.environ.setdefault("AUTH_JWT_SECRET", "test-secret-not-for-production-use-only")
os.environ.setdefault("AUTHSVC_ENVIRONMENT", "test")

import pytest  # noqa: E402
from fastapi.testclient import TestClient  # noqa: E402

from app.main import app  # noqa: E402


@pytest.fixture
def client():
    """TestClient against the real app — each test gets a fresh in-memory
    user/organization/revocation store via the lifespan's init_repository()."""
    with TestClient(app) as c:
        yield c


from features.account_ids import ADMIN_ACCOUNT_UUID  # noqa: E402

ADMIN_ACCOUNT_ID = ADMIN_ACCOUNT_UUID
"""Mirrors auth_settings.admin_account_id — membership of this app account is
what makes a user an administrator (features/dependencies.py::require_admin).

Imported rather than written out so the suite tracks the derivation in
features/account_ids.py instead of pinning a literal that would silently stop
matching if the namespace ever changed."""


def create_account(client, token: str, name: str, **fields) -> dict:
    """Register an app account and return the created record.

    account_id is generated by the service now, so tests read it off the
    response instead of choosing it.
    """
    r = client.post(
        "/auth/accounts",
        json={"name": name, **fields},
        headers=auth_headers(token),
    )
    assert r.status_code == 201, r.text
    return r.json()


def selected_account(user: dict) -> str | None:
    """The account a response says the session is scoped to.

    UserPublic no longer carries a flat account_id — the scoped account is the
    entry of `accounts` marked `selected`.
    """
    return next((a["account_id"] for a in user.get("accounts", []) if a.get("selected")), None)


def account_ids(user: dict) -> list[str]:
    """Every account a response says the user may sign in through."""
    return [a["account_id"] for a in user.get("accounts", [])]


def register(client, email: str, name: str, password: str = "hunter22") -> tuple[str, dict]:
    r = client.post("/auth/register", json={"email": email, "name": name, "password": password})
    assert r.status_code == 201, r.text
    body = r.json()
    return body["access_token"], body["user"]


_loop = None


def run_async(coro):
    """Run ``coro`` on one loop shared by the whole test session.

    Tests reach into the async repositories from sync test bodies, and there
    are two wrong ways to do it. ``asyncio.run`` creates a loop and then
    CLOSES it, leaving no current loop — which makes the next
    ``get_event_loop()`` in another test raise "There is no current event loop"
    purely because of the order tests ran in. ``get_event_loop()`` on its own
    is deprecated and creates a loop implicitly. One long-lived loop, created
    once and never closed, avoids both.

    Safe only because the suite is always on in-memory repositories
    (AUTH_MONGO_URI is forced empty at the top of this file): those are plain
    dicts with no event-loop affinity, so this loop can write to the same
    objects the TestClient's own loop reads. It would NOT be safe against
    Motor, which binds sockets to the loop that opened them.
    """
    global _loop
    import asyncio

    if _loop is None or _loop.is_closed():
        _loop = asyncio.new_event_loop()
    asyncio.set_event_loop(_loop)
    return _loop.run_until_complete(coro)


def seed_admin_account() -> None:
    """Create the admin app account, the way an operator does.

    Starting the service no longer creates ANY account (app/main.py), so a
    fresh store has no admin account and registering into it 404s. This is the
    test-suite equivalent of running scripts/seed_admin.py: it calls the same
    ensure_admin_account() that script does, rather than reaching into a
    repository, so the fixture exercises the real escape hatch instead of a
    shortcut the product does not have.
    """
    from features.app_accounts import ensure_admin_account

    run_async(ensure_admin_account())


def admin_token(client, email: str = "admin@richminds.io", password: str = "hunter22") -> str:
    """Seed the admin account, register the first administrator, return a token.

    Two steps now, because neither happens on its own: nothing creates the
    admin account at startup, and self-registration into it is allowed exactly
    once per store (see service.register). Each test gets a fresh in-memory
    store, so this works once per test — call it before any other admin exists.
    """
    seed_admin_account()
    r = client.post(
        "/auth/register",
        json={
            "email": email,
            "name": "Admin",
            "password": password,
            "account_id": ADMIN_ACCOUNT_ID,
        },
    )
    assert r.status_code == 201, r.text
    return r.json()["access_token"]


def auth_headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}"}
